<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Company>Rocky Stack</Company>
    <Product>Agent-X</Product>
    <Copyright>Copyright (c) 2026 Rocky Stack. All rights reserved.</Copyright>
    <Version>1.4.0</Version>
    <Authors>Rocky Stack</Authors>
  </PropertyGroup>
</Project>
