<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Company>Rocky Elsalaymeh</Company>
    <Product>Agent-X</Product>
    <Copyright>Copyright (c) 2026 Rocky Elsalaymeh. MIT License.</Copyright>
    <Version>2.1.0-preview.1</Version>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <FileVersion>2.1.0.0</FileVersion>
    <InformationalVersion>2.1.0-preview.1+bedrock</InformationalVersion>
    <Authors>Rocky Elsalaymeh</Authors>
  </PropertyGroup>
</Project>
