// <auto-generated />
using System;
using AgentX.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentX.Core.Data.Migrations
{
    [DbContext(typeof(AgentXDbContext))]
    [Migration("20260418041030_RemoveEncryptionColumns")]
    partial class RemoveEncryptionColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AgentX.Core.Data.Entities.AnnotationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChunkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("yellow");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HighlightedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartOffset")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId");

                    b.HasIndex("Color");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DocumentId");

                    b.ToTable("annotations", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.BackupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("manual");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double>("SizeMB")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BackupType");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsValid");

                    b.ToTable("backups", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.CollectionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconGlyph")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentCollectionId");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.ConversationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchLabel")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BranchPointMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchPointMessageId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsPinned");

                    b.HasIndex("ParentConversationId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.ConversationTagEntity", b =>
                {
                    b.Property<long>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("conversation_tags", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.DigestReportEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileTypeBreakdownJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightsJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewConversationsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewDocumentsCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<long>("StorageDeltaBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopCollectionsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopSearchesJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSearches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTokensUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("IsRead");

                    b.ToTable("digest_reports", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.DocumentChunkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndCharOffset")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmbedded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartCharOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("VectorRowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VectorRowId");

                    b.HasIndex("DocumentId", "ChunkIndex");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.DocumentCollectionEntity", b =>
                {
                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("document_collections", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.DocumentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FileModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndexingError")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndexingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastIndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("FileName");

                    b.HasIndex("FileType");

                    b.HasIndex("ImportedAt");

                    b.HasIndex("IndexingStatus");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.DocumentTagEntity", b =>
                {
                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.HasKey("DocumentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("document_tags", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.FeedbackEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackNote")
                        .HasColumnType("TEXT");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("none");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("Rating");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.InboxItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Preview")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCategory")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePluginId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<long?>("SuggestedCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuggestedCollectionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedTags")
                        .HasColumnType("TEXT");

                    b.Property<long?>("WatchFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddedAt");

                    b.HasIndex("DocumentId");

                    b.HasIndex("Status");

                    b.HasIndex("WatchFolderId");

                    b.HasIndex("ExternalId", "SourcePluginId");

                    b.ToTable("inbox_items", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.IndexingJobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunksProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmbeddingsGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProcessingTimeMs")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("queued");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("QueuedAt");

                    b.HasIndex("Status");

                    b.ToTable("indexing_jobs", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.LicenseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastValidatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("starter");

                    b.HasKey("Id");

                    b.ToTable("licenses", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.MemoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("fact");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Importance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.5);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Importance");

                    b.HasIndex("IsActive");

                    b.ToTable("memories", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CitationsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("GenerationTimeMs")
                        .HasColumnType("REAL");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "SortOrder");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.OAuthCredentialEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.ToTable("oauth_credentials", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.PluginEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Custom");

                    b.Property<string>("ReadmeContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstalledAt");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name");

                    b.HasIndex("PluginId")
                        .IsUnique();

                    b.HasIndex("PluginType");

                    b.ToTable("plugins", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.SearchHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectionFilter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateAfter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateBefore")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxResults")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MinScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("semantic");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SortOrder")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchedAt");

                    b.ToTable("search_history", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.SyncLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangesApplied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConflictsDetected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConflictsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Direction");

                    b.HasIndex("IsSuccess");

                    b.HasIndex("SyncedAt");

                    b.ToTable("sync_logs", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.SystemPromptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("General");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("system_prompts", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.TagEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.UserSettingsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("string");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.WatchFolderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileTypeFilter")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeSubfolders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScanAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TargetCollectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.HasIndex("TargetCollectionId");

                    b.ToTable("watch_folders", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.WorkflowEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Custom");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RunCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsBuiltIn");

                    b.HasIndex("IsEnabled");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.WorkflowRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalOutput")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialInput")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<string>("StepOutputsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("StepsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTokensUsed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowId");

                    b.ToTable("workflow_runs", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.WorkflowStepEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxTokensOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelOverride")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("AiPrompt");

                    b.Property<double?>("TemperatureOverride")
                        .HasColumnType("REAL");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "StepOrder");

                    b.ToTable("workflow_steps", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.WorkspaceProfileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveCollectionIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveModelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomSettings")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDefault");

                    b.ToTable("workspace_profiles", (string)null);
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.AnnotationEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.DocumentEntity", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.CollectionEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.CollectionEntity", "ParentCollection")
                        .WithMany("ChildCollections")
                        .HasForeignKey("ParentCollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCollection");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.ConversationEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.ConversationEntity", "ParentConversation")
                        .WithMany("Branches")
                        .HasForeignKey("ParentConversationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentConversation");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.ConversationTagEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.ConversationEntity", "Conversation")
                        .WithMany("ConversationTags")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentX.Core.Data.Entities.TagEntity", "Tag")
                        .WithMany("ConversationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.DocumentChunkEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.DocumentEntity", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.DocumentCollectionEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.CollectionEntity", "Collection")
                        .WithMany("DocumentCollections")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentX.Core.Data.Entities.DocumentEntity", "Document")
                        .WithMany("DocumentCollections")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.DocumentTagEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.DocumentEntity", "Document")
                        .WithMany("DocumentTags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentX.Core.Data.Entities.TagEntity", "Tag")
                        .WithMany("DocumentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.FeedbackEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.MessageEntity", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.IndexingJobEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.DocumentEntity", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.MessageEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.ConversationEntity", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.WatchFolderEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.CollectionEntity", "TargetCollection")
                        .WithMany()
                        .HasForeignKey("TargetCollectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TargetCollection");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.WorkflowRunEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.WorkflowEntity", "Workflow")
                        .WithMany("Runs")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.WorkflowStepEntity", b =>
                {
                    b.HasOne("AgentX.Core.Data.Entities.WorkflowEntity", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.CollectionEntity", b =>
                {
                    b.Navigation("ChildCollections");

                    b.Navigation("DocumentCollections");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.ConversationEntity", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("ConversationTags");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("DocumentCollections");

                    b.Navigation("DocumentTags");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.TagEntity", b =>
                {
                    b.Navigation("ConversationTags");

                    b.Navigation("DocumentTags");
                });

            modelBuilder.Entity("AgentX.Core.Data.Entities.WorkflowEntity", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
