using AgentX.Core.Data;
using AgentX.Core.Data.Entities;
using AgentX.Core.Services.Intelligence.Models;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace AgentX.Core.Services.Intelligence;

/// <summary>
/// Builds a knowledge graph from the document vault by loading all documents,
/// collections, and tags, creating nodes and edges for their relationships,
/// and applying a force-directed layout algorithm to produce spatial positions
/// suitable for visualization.
/// </summary>
public class KnowledgeGraphService : IKnowledgeGraphService
{
    private readonly AgentXDbContext _db;
    private readonly ILogger _log;

    // ── Force-directed layout parameters ────────────────────────────
    private const double RepulsionStrength = 5000.0;
    private const double AttractionStrength = 0.01;
    private const double IdealEdgeLength = 100.0;
    private const double CenterGravity = 0.01;
    private const double Damping = 0.85;
    private const int LayoutIterations = 100;
    private const double CanvasExtent = 1000.0;
    private const double MinDistance = 1.0;

    // ── Node color constants ────────────────────────────────────────
    private const string DocumentColor = "#3B82F6";  // Blue
    private const string CollectionColor = "#8B5CF6"; // Purple
    private const string TagColor = "#F59E0B";        // Amber

    // ── Edge color constants ────────────────────────────────────────
    private const string DocToCollectionEdgeColor = "#6366F1"; // Indigo
    private const string DocToTagEdgeColor = "#D97706";        // Amber-dark
    private const string DocToDocEdgeColor = "#374151";        // Gray

    public KnowledgeGraphService(AgentXDbContext db, ILogger logger)
    {
        _db = db ?? throw new ArgumentNullException(nameof(db));
        _log = logger?.ForContext<KnowledgeGraphService>()
               ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc />
    public async Task<KnowledgeGraphData> BuildGraphAsync(CancellationToken ct = default)
    {
        _log.Information("Building knowledge graph from vault data");

        // ── 1. Load all entities ─────────────────────────────────────
        var documents = await _db.Documents
            .Include(d => d.DocumentCollections).ThenInclude(dc => dc.Collection)
            .Include(d => d.DocumentTags).ThenInclude(dt => dt.Tag)
            .AsNoTracking()
            .ToListAsync(ct)
            .ConfigureAwait(false);

        var collections = await _db.Collections
            .AsNoTracking()
            .ToListAsync(ct)
            .ConfigureAwait(false);

        var tags = await _db.Tags
            .AsNoTracking()
            .ToListAsync(ct)
            .ConfigureAwait(false);

        _log.Debug(
            "Loaded {DocCount} documents, {ColCount} collections, {TagCount} tags",
            documents.Count, collections.Count, tags.Count);

        // ── 2. Build node and edge lists ─────────────────────────────
        var nodeLookup = new Dictionary<string, GraphNode>();
        var edges = new List<GraphEdge>();

        // Create document nodes
        foreach (var doc in documents)
        {
            var nodeId = $"doc-{doc.Id}";
            var size = Math.Clamp(14 + doc.ChunkCount * 2, 14, 40);

            var node = new GraphNode
            {
                Id = nodeId,
                Label = doc.FileName,
                NodeType = GraphNodeType.Document,
                ColorHex = DocumentColor,
                Size = size,
                EntityId = doc.Id,
                Subtitle = doc.FileType.ToUpperInvariant(),
            };

            nodeLookup[nodeId] = node;
        }

        // Create collection nodes
        foreach (var col in collections)
        {
            var nodeId = $"col-{col.Id}";
            var node = new GraphNode
            {
                Id = nodeId,
                Label = col.Name,
                NodeType = GraphNodeType.Collection,
                ColorHex = CollectionColor,
                Size = 32,
                EntityId = col.Id,
                Subtitle = $"{col.DocumentCount} docs",
            };

            nodeLookup[nodeId] = node;
        }

        // Create tag nodes
        foreach (var tag in tags)
        {
            var nodeId = $"tag-{tag.Id}";
            var node = new GraphNode
            {
                Id = nodeId,
                Label = tag.Name,
                NodeType = GraphNodeType.Tag,
                ColorHex = TagColor,
                Size = 16,
                EntityId = tag.Id,
                Subtitle = tag.IsAutoGenerated ? "auto" : "manual",
            };

            nodeLookup[nodeId] = node;
        }

        // ── 3. Create edges ──────────────────────────────────────────

        // Document -> Collection edges
        foreach (var doc in documents)
        {
            var docNodeId = $"doc-{doc.Id}";

            foreach (var dc in doc.DocumentCollections)
            {
                var colNodeId = $"col-{dc.CollectionId}";

                if (nodeLookup.ContainsKey(colNodeId))
                {
                    edges.Add(new GraphEdge
                    {
                        SourceId = docNodeId,
                        TargetId = colNodeId,
                        Label = "in collection",
                        Weight = 1.5,
                        ColorHex = DocToCollectionEdgeColor,
                    });
                }
            }

            // Document -> Tag edges
            foreach (var dt in doc.DocumentTags)
            {
                var tagNodeId = $"tag-{dt.TagId}";

                if (nodeLookup.ContainsKey(tagNodeId))
                {
                    edges.Add(new GraphEdge
                    {
                        SourceId = docNodeId,
                        TargetId = tagNodeId,
                        Label = "tagged",
                        Weight = 1.0,
                        ColorHex = DocToTagEdgeColor,
                    });
                }
            }
        }

        // Document <-> Document edges when they share a collection or tag.
        // Weight is the count of shared connections.
        var docDocEdges = BuildDocumentToDocumentEdges(documents);
        edges.AddRange(docDocEdges);

        // ── 4. Set connection counts ─────────────────────────────────
        foreach (var edge in edges)
        {
            if (nodeLookup.TryGetValue(edge.SourceId, out var sourceNode))
                sourceNode.ConnectionCount++;

            if (nodeLookup.TryGetValue(edge.TargetId, out var targetNode))
                targetNode.ConnectionCount++;
        }

        // ── 5. Assign initial random positions ──────────────────────
        var nodes = nodeLookup.Values.ToList();
        AssignRandomPositions(nodes);

        // ── 6. Run force-directed layout ────────────────────────────
        RunForceDirectedLayout(nodes, edges, nodeLookup);

        _log.Information(
            "Knowledge graph built: {NodeCount} nodes, {EdgeCount} edges",
            nodes.Count, edges.Count);

        return new KnowledgeGraphData
        {
            Nodes = nodes,
            Edges = edges,
            DocumentCount = documents.Count,
            CollectionCount = collections.Count,
            TagCount = tags.Count,
        };
    }

    // ═══════════════════════════════════════════════════════════════════
    //  PRIVATE HELPERS
    // ═══════════════════════════════════════════════════════════════════

    /// <summary>
    /// Builds document-to-document edges for all pairs of documents that
    /// share at least one collection or tag. The edge weight equals the
    /// number of shared connections.
    /// </summary>
    private static List<GraphEdge> BuildDocumentToDocumentEdges(List<DocumentEntity> documents)
    {
        var result = new List<GraphEdge>();

        // Build lookup: for each collection/tag ID, which document IDs contain it
        var collectionToDocIds = new Dictionary<long, List<long>>();
        var tagToDocIds = new Dictionary<long, List<long>>();

        foreach (var doc in documents)
        {
            foreach (var dc in doc.DocumentCollections)
            {
                if (!collectionToDocIds.TryGetValue(dc.CollectionId, out var list))
                {
                    list = new List<long>();
                    collectionToDocIds[dc.CollectionId] = list;
                }
                list.Add(doc.Id);
            }

            foreach (var dt in doc.DocumentTags)
            {
                if (!tagToDocIds.TryGetValue(dt.TagId, out var list))
                {
                    list = new List<long>();
                    tagToDocIds[dt.TagId] = list;
                }
                list.Add(doc.Id);
            }
        }

        // Count shared connections per pair
        var pairWeights = new Dictionary<(long, long), int>();

        void CountPairs(Dictionary<long, List<long>> groupToDocIds)
        {
            foreach (var (_, docIds) in groupToDocIds)
            {
                for (int i = 0; i < docIds.Count; i++)
                {
                    for (int j = i + 1; j < docIds.Count; j++)
                    {
                        var lo = Math.Min(docIds[i], docIds[j]);
                        var hi = Math.Max(docIds[i], docIds[j]);
                        var key = (lo, hi);

                        pairWeights.TryGetValue(key, out var count);
                        pairWeights[key] = count + 1;
                    }
                }
            }
        }

        CountPairs(collectionToDocIds);
        CountPairs(tagToDocIds);

        // Create edges from pair weights
        foreach (var ((docA, docB), weight) in pairWeights)
        {
            result.Add(new GraphEdge
            {
                SourceId = $"doc-{docA}",
                TargetId = $"doc-{docB}",
                Label = $"{weight} shared",
                Weight = weight,
                ColorHex = DocToDocEdgeColor,
            });
        }

        return result;
    }

    /// <summary>
    /// Assigns initial random positions spread across the canvas extent,
    /// using a deterministic seed for reproducible layouts.
    /// </summary>
    private static void AssignRandomPositions(List<GraphNode> nodes)
    {
        var rng = new Random(42); // Deterministic seed for reproducibility

        foreach (var node in nodes)
        {
            node.X = (rng.NextDouble() - 0.5) * CanvasExtent;
            node.Y = (rng.NextDouble() - 0.5) * CanvasExtent;
            node.Vx = 0;
            node.Vy = 0;
        }
    }

    /// <summary>
    /// Runs a simple spring-electric force-directed layout algorithm.
    /// Uses repulsion between all node pairs, attraction along edges,
    /// and a centering gravity force. Applies velocity damping each iteration.
    /// </summary>
    private static void RunForceDirectedLayout(
        List<GraphNode> nodes,
        List<GraphEdge> edges,
        Dictionary<string, GraphNode> nodeLookup)
    {
        if (nodes.Count <= 1)
            return;

        for (int iteration = 0; iteration < LayoutIterations; iteration++)
        {
            // ── Repulsion between all pairs ──────────────────────────
            for (int i = 0; i < nodes.Count; i++)
            {
                for (int j = i + 1; j < nodes.Count; j++)
                {
                    var ni = nodes[i];
                    var nj = nodes[j];

                    var dx = nj.X - ni.X;
                    var dy = nj.Y - ni.Y;
                    var distSq = dx * dx + dy * dy;
                    var dist = Math.Max(Math.Sqrt(distSq), MinDistance);

                    var force = RepulsionStrength / (dist * dist);
                    var fx = (dx / dist) * force;
                    var fy = (dy / dist) * force;

                    ni.Vx -= fx;
                    ni.Vy -= fy;
                    nj.Vx += fx;
                    nj.Vy += fy;
                }
            }

            // ── Attraction along edges ───────────────────────────────
            foreach (var edge in edges)
            {
                if (!nodeLookup.TryGetValue(edge.SourceId, out var source))
                    continue;
                if (!nodeLookup.TryGetValue(edge.TargetId, out var target))
                    continue;

                var dx = target.X - source.X;
                var dy = target.Y - source.Y;
                var dist = Math.Max(Math.Sqrt(dx * dx + dy * dy), MinDistance);

                var force = AttractionStrength * (dist - IdealEdgeLength);
                var fx = (dx / dist) * force;
                var fy = (dy / dist) * force;

                source.Vx += fx;
                source.Vy += fy;
                target.Vx -= fx;
                target.Vy -= fy;
            }

            // ── Center gravity ───────────────────────────────────────
            foreach (var node in nodes)
            {
                node.Vx -= node.X * CenterGravity;
                node.Vy -= node.Y * CenterGravity;
            }

            // ── Apply velocities with damping ────────────────────────
            foreach (var node in nodes)
            {
                node.Vx *= Damping;
                node.Vy *= Damping;
                node.X += node.Vx;
                node.Y += node.Vy;
            }
        }
    }
}
