namespace AgentX.Core.Data.Entities;

public class TagEntity
{
    public long Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? ColorHex { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }

    // Navigation
    public ICollection<DocumentTagEntity> DocumentTags { get; set; } = new List<DocumentTagEntity>();
    public ICollection<ConversationTagEntity> ConversationTags { get; set; } = new List<ConversationTagEntity>();
}
